# Generated by Django 4.2.6 on 2023-11-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banner_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
            preserve_default=False,
        ),
    ]
