# Generated by Django 3.2.18 on 2023-10-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231023_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_orders',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
