# Generated by Django 3.2.18 on 2023-10-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='user',
            new_name='by',
        ),
    ]
