# Generated by Django 4.2.6 on 2023-10-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
