# Generated by Django 4.2.6 on 2023-10-29 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.address'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dislikes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
