# Generated by Django 4.2.6 on 2023-10-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_product_dislikes_alter_product_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
