# Generated by Django 4.2.6 on 2023-10-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
